# DocSync AI Workflow Example - FIXED VERSION
# Place this file in your repository at: .github/workflows/docsync-ai.yml
# This workflow will trigger when a PR is merged to your base branch

name: 📚 DocSync AI Documentation

on:
  pull_request:
    types: [closed]
    branches:
      - master  # Change to 'main' if your default branch is 'main'

  # NEW: Trigger on comments for @docsync refinement feature
  issue_comment:
    types: [created]

# IMPORTANT: Add permissions here for the calling workflow
permissions:
  contents: write        # Required to create branches and push changes
  pull-requests: write   # Required to create PRs
  issues: write          # NEW: Required for @docsync comment refinement

jobs:
  # Job 1: Update documentation when PR is merged
  update-documentation:
    # Only run when PR is actually merged (not just closed)
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    uses: akash-deriv/shared-actions/.github/workflows/docsync-ai.yml@master
    with:
      # Base branch for documentation PR (default: 'master')
      base_branch: 'master'  # Change to 'main' if needed

      # Labels to add to the documentation PR
      pr_labels: 'documentation,automated,docsync-ai'

      # (Optional) Repository owner's Slack user ID for notifications
      # Example: 'U0123456789'
      repository_owner: 'U0AA8EH0QD8'  # Leave empty if you don't want to tag anyone

    secrets:
      # GitHub Personal Access Token with repo and pull_requests permissions
      # Create this token at: https://github.com/settings/tokens/new
      # Required scopes: repo, workflow
      DOCSYNC_GITHUB_TOKEN: ${{ secrets.DOCSYNC_GITHUB_TOKEN }}

      # Anthropic API Key for Claude AI
      # Get your API key from: https://console.anthropic.com/
      DOCSYNC_ANTHROPIC_API_KEY: ${{ secrets.DOCSYNC_ANTHROPIC_API_KEY }}

      # (Optional) Slack Webhook URL for notifications
      # Create a webhook at: https://api.slack.com/messaging/webhooks
      DOCSYNC_SLACK_WEBHOOK: ${{ secrets.DOCSYNC_SLACK_WEBHOOK }}

  # Job 2: NEW - Refine documentation based on @docsync comments
  refine-documentation:
    # Only run when someone comments on a PR
    if: github.event_name == 'issue_comment'
    uses: akash-deriv/shared-actions/.github/workflows/docsync-ai-refine.yml@master
    secrets:
      # Reuse the same secrets
      DOCSYNC_GITHUB_TOKEN: ${{ secrets.DOCSYNC_GITHUB_TOKEN }}
      DOCSYNC_ANTHROPIC_API_KEY: ${{ secrets.DOCSYNC_ANTHROPIC_API_KEY }}
