# 📚 DocSync AI - Complete Workflow Template
#
# Copy this SINGLE file to your repository at:
# .github/workflows/docsync-ai.yml
#
# This workflow provides BOTH features:
# 1. Automatic documentation sync on PR merge
# 2. Human feedback refinement with @docsync comments

name: 📚 DocSync AI

on:
  # Trigger on PR merge for automatic documentation sync
  pull_request:
    types: [closed]
    branches:
      - master  # Change to 'main' if needed

  # Trigger on comments for refinement feature
  issue_comment:
    types: [created]

jobs:
  # Job 1: Automatic Documentation Sync (when PR is merged)
  sync-documentation:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    uses: akash-deriv/shared-actions/.github/workflows/docsync-ai.yml@master
    with:
      base_branch: 'master'  # Change to 'main' if needed
      pr_labels: 'documentation,automated'
      repository_owner: ''  # Optional: Your Slack user ID (e.g., 'U12345678')
    secrets:
      DOCSYNC_GITHUB_TOKEN: ${{ secrets.DOCSYNC_GITHUB_TOKEN }}
      DOCSYNC_ANTHROPIC_API_KEY: ${{ secrets.DOCSYNC_ANTHROPIC_API_KEY }}
      DOCSYNC_SLACK_WEBHOOK: ${{ secrets.DOCSYNC_SLACK_WEBHOOK }}  # Optional

  # Job 2: Human Feedback Refinement (when @docsync is commented)
  refine-documentation:
    if: github.event_name == 'issue_comment'
    uses: akash-deriv/shared-actions/.github/workflows/docsync-ai-refine.yml@master
    secrets:
      DOCSYNC_GITHUB_TOKEN: ${{ secrets.DOCSYNC_GITHUB_TOKEN }}
      DOCSYNC_ANTHROPIC_API_KEY: ${{ secrets.DOCSYNC_ANTHROPIC_API_KEY }}
